from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(420, 314)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 421, 311))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.menu = QtGui.QTabWidget(self.verticalLayoutWidget)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.Cadastros = QtGui.QWidget()
        self.Cadastros.setObjectName(_fromUtf8("Cadastros"))
        self.frame = QtGui.QFrame(self.Cadastros)
        self.frame.setGeometry(QtCore.QRect(0, 0, 411, 281))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.button_Cadastrar_livro = QtGui.QPushButton(self.frame)
        self.button_Cadastrar_livro.setGeometry(QtCore.QRect(300, 60, 85, 27))
        self.button_Cadastrar_livro.setObjectName(_fromUtf8("button_Cadastrar_livro"))
        self.button_Cancelar = QtGui.QPushButton(self.frame)
        self.button_Cancelar.setGeometry(QtCore.QRect(20, 240, 85, 27))
        self.button_Cancelar.setObjectName(_fromUtf8("button_Cancelar"))
        self.label_nome_livros = QtGui.QLabel(self.frame)
        self.label_nome_livros.setGeometry(QtCore.QRect(20, 40, 54, 17))
        self.label_nome_livros.setObjectName(_fromUtf8("label_nome_livros"))
        self.label_quatidade_livros = QtGui.QLabel(self.frame)
        self.label_quatidade_livros.setGeometry(QtCore.QRect(160, 40, 71, 17))
        self.label_quatidade_livros.setObjectName(_fromUtf8("label_quatidade_livros"))
        self.editText_nome_livros = QtGui.QLineEdit(self.frame)
        self.editText_nome_livros.setGeometry(QtCore.QRect(20, 60, 113, 29))
        self.editText_nome_livros.setObjectName(_fromUtf8("editText_nome_livros"))
        self.editText_quantidade_livros = QtGui.QLineEdit(self.frame)
        self.editText_quantidade_livros.setGeometry(QtCore.QRect(150, 60, 113, 29))
        self.editText_quantidade_livros.setObjectName(_fromUtf8("editText_quantidade_livros"))
        self.Label_Livros = QtGui.QLabel(self.frame)
        self.Label_Livros.setGeometry(QtCore.QRect(10, 10, 111, 17))
        self.Label_Livros.setObjectName(_fromUtf8("Label_Livros"))
        self.label_Usuarios = QtGui.QLabel(self.frame)
        self.label_Usuarios.setGeometry(QtCore.QRect(10, 100, 131, 17))
        self.label_Usuarios.setObjectName(_fromUtf8("label_Usuarios"))
        self.editText_nome_usuario = QtGui.QLineEdit(self.frame)
        self.editText_nome_usuario.setGeometry(QtCore.QRect(20, 150, 113, 29))
        self.editText_nome_usuario.setObjectName(_fromUtf8("editText_nome_usuario"))
        self.label_nome_usuarios = QtGui.QLabel(self.frame)
        self.label_nome_usuarios.setGeometry(QtCore.QRect(20, 130, 54, 17))
        self.label_nome_usuarios.setObjectName(_fromUtf8("label_nome_usuarios"))
        self.label_cpf = QtGui.QLabel(self.frame)
        self.label_cpf.setGeometry(QtCore.QRect(160, 130, 54, 17))
        self.label_cpf.setObjectName(_fromUtf8("label_cpf"))
        self.editText_cpf_usuario = QtGui.QLineEdit(self.frame)
        self.editText_cpf_usuario.setGeometry(QtCore.QRect(150, 150, 113, 29))
        self.editText_cpf_usuario.setObjectName(_fromUtf8("editText_cpf_usuario"))
        self.button_Cadastrar_usuario = QtGui.QPushButton(self.frame)
        self.button_Cadastrar_usuario.setGeometry(QtCore.QRect(300, 150, 85, 27))
        self.button_Cadastrar_usuario.setObjectName(_fromUtf8("button_Cadastrar_usuario"))
        self.menu.addTab(self.Cadastros, _fromUtf8(""))
        self.Biblioteca = QtGui.QWidget()
        self.Biblioteca.setObjectName(_fromUtf8("Biblioteca"))
        self.frame_2 = QtGui.QFrame(self.Biblioteca)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 411, 281))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.button_Cancelar_2 = QtGui.QPushButton(self.frame_2)
        self.button_Cancelar_2.setGeometry(QtCore.QRect(10, 240, 85, 27))
        self.button_Cancelar_2.setObjectName(_fromUtf8("button_Cancelar_2"))
        self.editText_buscar_usuario = QtGui.QLineEdit(self.frame_2)
        self.editText_buscar_usuario.setGeometry(QtCore.QRect(290, 0, 113, 29))
        self.editText_buscar_usuario.setObjectName(_fromUtf8("editText_buscar_usuario"))
        self.textView_Nome_usuario = QtGui.QLabel(self.frame_2)
        self.textView_Nome_usuario.setGeometry(QtCore.QRect(10, 10, 54, 17))
        self.textView_Nome_usuario.setObjectName(_fromUtf8("textView_Nome_usuario"))
        self.textView_nome_Livro = QtGui.QLabel(self.frame_2)
        self.textView_nome_Livro.setGeometry(QtCore.QRect(10, 110, 54, 17))
        self.textView_nome_Livro.setObjectName(_fromUtf8("textView_nome_Livro"))
        self.editText_buscar_livro = QtGui.QLineEdit(self.frame_2)
        self.editText_buscar_livro.setGeometry(QtCore.QRect(290, 100, 113, 29))
        self.editText_buscar_livro.setObjectName(_fromUtf8("editText_buscar_livro"))
        self.button_buscar_usuario = QtGui.QPushButton(self.frame_2)
        self.button_buscar_usuario.setGeometry(QtCore.QRect(320, 30, 85, 27))
        self.button_buscar_usuario.setObjectName(_fromUtf8("button_buscar_usuario"))
        self.button_buscar_livro = QtGui.QPushButton(self.frame_2)
        self.button_buscar_livro.setGeometry(QtCore.QRect(320, 130, 85, 27))
        self.button_buscar_livro.setObjectName(_fromUtf8("button_buscar_livro"))
        self.textView_isDisponivel = QtGui.QLabel(self.frame_2)
        self.textView_isDisponivel.setGeometry(QtCore.QRect(150, 110, 111, 17))
        self.textView_isDisponivel.setObjectName(_fromUtf8("textView_isDisponivel"))
        self.label_quantidade = QtGui.QLabel(self.frame_2)
        self.label_quantidade.setGeometry(QtCore.QRect(10, 140, 81, 17))
        self.label_quantidade.setTextFormat(QtCore.Qt.RichText)
        self.label_quantidade.setObjectName(_fromUtf8("label_quantidade"))
        self.textView_Quantidade = QtGui.QLabel(self.frame_2)
        self.textView_Quantidade.setGeometry(QtCore.QRect(110, 140, 54, 17))
        self.textView_Quantidade.setObjectName(_fromUtf8("textView_Quantidade"))
        self.button_devolver = QtGui.QPushButton(self.frame_2)
        self.button_devolver.setGeometry(QtCore.QRect(120, 240, 85, 27))
        self.button_devolver.setObjectName(_fromUtf8("button_devolver"))
        self.button_reservar = QtGui.QPushButton(self.frame_2)
        self.button_reservar.setGeometry(QtCore.QRect(220, 240, 85, 27))
        self.button_reservar.setObjectName(_fromUtf8("button_reservar"))
        self.button_alugar = QtGui.QPushButton(self.frame_2)
        self.button_alugar.setGeometry(QtCore.QRect(320, 240, 85, 27))
        self.button_alugar.setObjectName(_fromUtf8("button_alugar"))
        self.list_Alugados = QtGui.QListView(self.frame_2)
        self.list_Alugados.setGeometry(QtCore.QRect(10, 30, 281, 51))
        self.list_Alugados.setFlow(QtGui.QListView.LeftToRight)
        self.list_Alugados.setObjectName(_fromUtf8("list_Alugados"))
        self.list_Alugou = QtGui.QListView(self.frame_2)
        self.list_Alugou.setGeometry(QtCore.QRect(10, 170, 381, 51))
        self.list_Alugou.setFlow(QtGui.QListView.LeftToRight)
        self.list_Alugou.setObjectName(_fromUtf8("list_Alugou"))
        self.menu.addTab(self.Biblioteca, _fromUtf8(""))
        self.verticalLayout.addWidget(self.menu)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.menu.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Biblioteca", None))
        self.button_Cadastrar_livro.setText(_translate("MainWindow", "Cadastrar", None))
        self.button_Cancelar.setText(_translate("MainWindow", "Cancelar", None))
        self.label_nome_livros.setText(_translate("MainWindow", "Nome", None))
        self.label_quatidade_livros.setText(_translate("MainWindow", "Quantidade", None))
        self.Label_Livros.setText(_translate("MainWindow", "Cadastro De Livros", None))
        self.label_Usuarios.setText(_translate("MainWindow", "Cadastro De Usuarios", None))
        self.label_nome_usuarios.setText(_translate("MainWindow", "Nome", None))
        self.label_cpf.setText(_translate("MainWindow", "CPF", None))
        self.button_Cadastrar_usuario.setText(_translate("MainWindow", "Cadastrar", None))
        self.menu.setTabText(self.menu.indexOf(self.Cadastros), _translate("MainWindow", "Cadastros", None))
        self.button_Cancelar_2.setText(_translate("MainWindow", "Cancelar", None))
        self.textView_Nome_usuario.setText(_translate("MainWindow", "Usuario", None))
        self.textView_nome_Livro.setText(_translate("MainWindow", "Livro", None))
        self.button_buscar_usuario.setText(_translate("MainWindow", "Buscar", None))
        self.button_buscar_livro.setText(_translate("MainWindow", "Buscar", None))
        self.textView_isDisponivel.setText(_translate("MainWindow", "Disponivel", None))
        self.label_quantidade.setText(_translate("MainWindow", "Quantidade:", None))
        self.textView_Quantidade.setText(_translate("MainWindow", "numeros", None))
        self.button_devolver.setText(_translate("MainWindow", "Devolver", None))
        self.button_reservar.setText(_translate("MainWindow", "Reservar", None))
        self.button_alugar.setText(_translate("MainWindow", "Alugar", None))
        self.menu.setTabText(self.menu.indexOf(self.Biblioteca), _translate("MainWindow", "Biblioteca", None))


def run():
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

run()