from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def iniciarUi(self, MainWindow):
        MainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.menu = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.Cadastros = QtWidgets.QWidget()
        self.frame = QtWidgets.QFrame(self.Cadastros)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 571))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_Cadastrar_livro = QtWidgets.QPushButton(self.frame)
        self.button_Cadastrar_livro.setGeometry(QtCore.QRect(250, 150, 85, 27))
        self.button_Cancelar = QtWidgets.QPushButton(self.frame)
        self.button_Cancelar.setGeometry(QtCore.QRect(10, 530, 85, 27))
        self.label_nome_livros = QtWidgets.QLabel(self.frame)
        self.label_nome_livros.setGeometry(QtCore.QRect(10, 50, 54, 17))
        self.label_quatidade_livros = QtWidgets.QLabel(self.frame)
        self.label_quatidade_livros.setGeometry(QtCore.QRect(220, 50, 71, 17))
        self.editText_nome_livros = QtWidgets.QLineEdit(self.frame)
        self.editText_nome_livros.setGeometry(QtCore.QRect(10, 80, 113, 29))
        self.editText_quantidade_livros = QtWidgets.QLineEdit(self.frame)
        self.editText_quantidade_livros.setGeometry(QtCore.QRect(220, 80, 113, 29))
        self.Label_Livros = QtWidgets.QLabel(self.frame)
        self.Label_Livros.setGeometry(QtCore.QRect(10, 10, 111, 17))
        self.label_Usuarios = QtWidgets.QLabel(self.frame)
        self.label_Usuarios.setGeometry(QtCore.QRect(10, 210, 131, 17))
        self.editText_nome_usuario = QtWidgets.QLineEdit(self.frame)
        self.editText_nome_usuario.setGeometry(QtCore.QRect(20, 300, 113, 29))
        self.label_nome_usuarios = QtWidgets.QLabel(self.frame)
        self.label_nome_usuarios.setGeometry(QtCore.QRect(20, 270, 54, 17))
        self.label_cpf = QtWidgets.QLabel(self.frame)
        self.label_cpf.setGeometry(QtCore.QRect(220, 270, 54, 17))
        self.editText_cpf_usuario = QtWidgets.QLineEdit(self.frame)
        self.editText_cpf_usuario.setGeometry(QtCore.QRect(220, 300, 113, 29))
        self.button_Cadastrar_usuario = QtWidgets.QPushButton(self.frame)
        self.button_Cadastrar_usuario.setGeometry(QtCore.QRect(240, 390, 85, 27))
        self.button_Descadastrar_usuario = QtWidgets.QPushButton(self.frame)
        self.button_Descadastrar_usuario.setGeometry(QtCore.QRect(500, 530, 131, 27))
        self.button_Descadastrar_livro = QtWidgets.QPushButton(self.frame)
        self.button_Descadastrar_livro.setGeometry(QtCore.QRect(650, 530, 131, 27))
        self.menu.addTab(self.Cadastros, "")
        self.Biblioteca = QtWidgets.QWidget()
        self.frame_2 = QtWidgets.QFrame(self.Biblioteca)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 801, 571))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_Cancelar_2 = QtWidgets.QPushButton(self.frame_2)
        self.button_Cancelar_2.setGeometry(QtCore.QRect(10, 530, 85, 27))
        self.editText_buscar_usuario = QtWidgets.QLineEdit(self.frame_2)
        self.editText_buscar_usuario.setGeometry(QtCore.QRect(680, 0, 113, 29))
        self.textView_Nome_usuario = QtWidgets.QLabel(self.frame_2)
        self.textView_Nome_usuario.setGeometry(QtCore.QRect(10, 10, 54, 17))
        self.textView_nome_Livro = QtWidgets.QLabel(self.frame_2)
        self.textView_nome_Livro.setGeometry(QtCore.QRect(10, 240, 54, 17))
        self.editText_buscar_livro = QtWidgets.QLineEdit(self.frame_2)
        self.editText_buscar_livro.setGeometry(QtCore.QRect(680, 220, 113, 29))
        self.button_buscar_usuario = QtWidgets.QPushButton(self.frame_2)
        self.button_buscar_usuario.setGeometry(QtCore.QRect(710, 30, 85, 27))
        self.button_buscar_livro = QtWidgets.QPushButton(self.frame_2)
        self.button_buscar_livro.setGeometry(QtCore.QRect(710, 250, 85, 27))
        self.textView_isDisponivel = QtWidgets.QLabel(self.frame_2)
        self.textView_isDisponivel.setGeometry(QtCore.QRect(160, 240, 111, 17))
        self.label_quantidade = QtWidgets.QLabel(self.frame_2)
        self.label_quantidade.setGeometry(QtCore.QRect(10, 300, 81, 17))
        self.label_quantidade.setTextFormat(QtCore.Qt.RichText)
        self.textView_Quantidade = QtWidgets.QLabel(self.frame_2)
        self.textView_Quantidade.setGeometry(QtCore.QRect(100, 300, 54, 17))
        self.button_devolver = QtWidgets.QPushButton(self.frame_2)
        self.button_devolver.setGeometry(QtCore.QRect(180, 530, 85, 27))
        self.button_reservar = QtWidgets.QPushButton(self.frame_2)
        self.button_reservar.setGeometry(QtCore.QRect(280, 530, 85, 27))
        self.button_alugar = QtWidgets.QPushButton(self.frame_2)
        self.button_alugar.setGeometry(QtCore.QRect(700, 530, 85, 27))
        self.list_Alugados = QtWidgets.QListView(self.frame_2)
        self.list_Alugados.setGeometry(QtCore.QRect(10, 30, 471, 141))
        self.list_Alugados.setFlow(QtWidgets.QListView.LeftToRight)
        self.list_Alugou = QtWidgets.QListView(self.frame_2)
        self.list_Alugou.setGeometry(QtCore.QRect(10, 330, 471, 151))
        self.list_Alugou.setFlow(QtWidgets.QListView.LeftToRight)
        self.menu.addTab(self.Biblioteca, "")
        self.verticalLayout.addWidget(self.menu)
        MainWindow.setCentralWidget(self.centralWidget)

        self.nomearUi(MainWindow)
        self.menu.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def nomearUi(self, MainWindow):
        MainWindow.setWindowTitle("MainWindow")
        self.button_Cadastrar_livro.setText("Cadastrar")
        self.button_Cancelar.setText("Cancelar")
        self.label_nome_livros.setText("Nome")
        self.label_quatidade_livros.setText("Quantidade")
        self.Label_Livros.setText("Cadastro De Livros")
        self.label_Usuarios.setText("Cadastro De Usuarios")
        self.label_nome_usuarios.setText("Nome")
        self.label_cpf.setText( "CPF")
        self.button_Cadastrar_usuario.setText("Cadastrar")
        self.button_Descadastrar_usuario.setText("Descadastrar Usuario")
        self.button_Descadastrar_livro.setText("Descadastrar Livro")
        self.menu.setTabText(self.menu.indexOf(self.Cadastros), "Cadastros")
        self.button_Cancelar_2.setText( "Cancelar")
        self.textView_Nome_usuario.setText("Usuario")
        self.textView_nome_Livro.setText("Livro")
        self.button_buscar_usuario.setText("Buscar")
        self.button_buscar_livro.setText("Buscar")
        self.textView_isDisponivel.setText("Disponivel")
        self.label_quantidade.setText( "Quantidade:")
        self.textView_Quantidade.setText( "numeros")
        self.button_devolver.setText("Devolver")
        self.button_reservar.setText("Reservar")
        self.button_alugar.setText("Alugar")
        self.menu.setTabText(self.menu.indexOf(self.Biblioteca),"Biblioteca")

def run():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.iniciarUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

run()